### ISSUE TITLE
Release the ets copyright checker

### ISSUE THREAD

**Issue by rahulporuri** [enthought/ets-copyright-checker#3]
Once the code is moved over (#1 ) and CI is setup (#2 ), we should be able to make a release of the ets copyright checker package. Note that as part of the release process, eggs should be uploaded to PyPI (once a new PyPI project is created for this package).

**Comment by kitchoi** [comment]
Closing via #15. 
The release is tagged `1.0.0` and is now available on PyPI: https://pypi.org/project/flake8-ets/
Request for having the egg available from EDM has been made.
